# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 990850bf1bc2ca60bf14e9a5f385ee6b6154275ca4913ce151b6bdf85eaa48a3b65af341ac2c4aba7a2c536a6a45b1bf13b88e55b7a531f182ece0cd6e39c1e7
  stripe_publishable_key: pk_test_lIycvzL5yeuI3fWAD6TXXlbm
  stripe_secret_key: sk_test_jkPTRPH0EEqyweNBlvhR6ADf

test:
  secret_key_base: 4f51665e0c305a7c1003b08a053218187a2d390a812c7bdda28b4f0237c25453335c7faa6a52be182b223cee5e30af41815c596bf7ca0e999987b12998132483
  stripe_publishable_key: pk_test_lIycvzL5yeuI3fWAD6TXXlbm
  stripe_secret_key: sk_test_jkPTRPH0EEqyweNBlvhR6ADf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: ENV['STRIPE_PUBLISHABLE_KEY']
  stripe_secret_key: ENV['STRIPE_SECRET_KEY']
